version: '3'

services:
  gerrit:
    image: gerritcodereview/gerrit
    ports:
      - "29418:29418"
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
      - ldap
    volumes:
      - /home/vagrant/gerrit/etc:/var/gerrit/etc
      - /home/vagrant/gerrit/git:/var/gerrit/git
      - /home/vagrant/gerrit/index:/var/gerrit/index
      - /home/vagrant/gerrit/cache:/var/gerrit/cache
    entrypoint: java -jar /var/gerrit/bin/gerrit.war init -d /var/gerrit

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=gerrit
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=reviewdb
    volumes:
      - /home/vagrant/gerrit/postgres:/var/lib/postgresql/data

  ldap:
    image: osixia/openldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=secret
    volumes:
      - /home/vagrant/gerrit/ldap/var:/var/lib/ldap
      - /home/vagrant/gerrit/ldap/etc:/etc/ldap/slapd.d

  ldap-admin:
    image: osixia/phpldapadmin
    ports:
      - "6443:443"
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
